**Trabajo Práctico 1**

**Presentado por Esteban García Solís**

> 1) Implemente la función calcularTrazaMatriz la cual calcule la traza de una matriz usando únicamente operaciones básicas en pytorch (multiplicación, multiplicación por elemento, matriz identidad, etc.), prescindiendo de estructuras de repetición como el for el while.

In [1]:
import torch 
import numpy as np

def trace(A):
  return (A * torch.eye(A.shape[0])).sum()

A = torch.tensor([[2.0, 9.0, 3.0],
                  [2.0, -5.0, 4.0],
                  [3.0, 7.0, 6.0]])

B = torch.tensor([[1.0, 7.0, 1.0],
                  [0.0, 2.0, -4.0],
                  [3.0, 8.0, 3.0]])


print("Matrix: \n{}\nTrace:{}".format(A, trace(A)))
print("\nMatrix: \n{}\nTrace:{}".format(B, trace(B)))


Matrix: 
tensor([[ 2.,  9.,  3.],
        [ 2., -5.,  4.],
        [ 3.,  7.,  6.]])
Trace:3.0

Matrix: 
tensor([[ 1.,  7.,  1.],
        [ 0.,  2., -4.],
        [ 3.,  8.,  3.]])
Trace:6.0


> 4) Muestre con un ejemplo numérico que para un vector $\overrightarrow{x}\in\mathbb{R}^{n}$ y una matriz simétrica $A\in\mathbb{R}^{n\times n}$ que:$\left(\vec{x}^{T}\,A\,\vec{x}\right)^{T}=\vec{x}^{T}\,A\,\vec{x}$

>> a) Incluya el código en Pytorch que permita corroborar tal igualdad para cualquier matriz simétrica A y vector $\overrightarrow{x}\in\mathbb{R}^{n}$, generado aleatoriamente. Recuerde que a partir de cualquier matriz cuadrada A generada aleatoriamente puede calcularse una matriz simétrica, según lo discutido en clase. 

In [2]:
def symmetric(X):
  return 0.5 * (X + torch.transpose(X, 0 ,1))

def isSymmetric(X):
  return torch.equal(X, torch.transpose(X, 0 ,1))

def test(n):
  A = torch.rand(n, n)
  S = symmetric(A)
  x = torch.rand(n, 1)

  A1 = (x.transpose(0, 1).mm(A).mm(x)).transpose(0,1)
  A2 = x.transpose(0, 1).mm(A).mm(x)

  print("A=",A)
  print("x=",x)
  print("(xT A x)T=", A1)
  print("xT A x=", A2)

  print("Equal? ", torch.equal(A1, A2))

test(3)

A= tensor([[0.8695, 0.7860, 0.7581],
        [0.8588, 0.6003, 0.9073],
        [0.3219, 0.5903, 0.8861]])
x= tensor([[0.5818],
        [0.0579],
        [0.9836]])
(xT A x)T= tensor([[1.9122]])
xT A x= tensor([[1.9122]])
Equal?  True


> 8) La Matriz de covarianza (ver colab)
>> a) Escriba la función en Pytorch sin usar estructuras de repetición for o while, usando únicamente las funciones para cálculo de vector medio, y multiplicaciones matriciales. Documente su uso con el ejemplo descrito en este documento.

In [3]:
h1 = torch.tensor([2.0,   4.0,  6.0,  8.0])
h2 = torch.tensor([4.0,   8.0, 12.0, 16.0])
h3 = torch.tensor([12.0, 10.0,  5.0,  9.0])

A = torch.stack((h1, h2, h3))

def covar(A):
  A = A.transpose(0, 1)
  ones = torch.ones(A.shape[0], A.shape[0])
  B = A - ones.mm(A) * 1/A.shape[0]
  return (B.transpose(0, 1).mm(B)) /A.shape[1]

print("A=", A)
print("A Covariance: \n", covar(A))

A= tensor([[ 2.,  4.,  6.,  8.],
        [ 4.,  8., 12., 16.],
        [12., 10.,  5.,  9.]])
A Covariance: 
 tensor([[ 6.6667, 13.3333, -4.6667],
        [13.3333, 26.6667, -9.3333],
        [-4.6667, -9.3333,  8.6667]])
